server:
  port: 8088
---
spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**,
        # - id: delivery
        #   uri: http://localhost:8082
        #   predicates:
        #     - Path=/deliveries/**,
        # - id: product
        #   uri: http://localhost:8083
        #   predicates:
        #     - Path=/inventories/**,
        - id: pet
          uri: http://localhost:8082
          predicates:
            - Path=/pets/**,
        - id: feed
          uri: http://localhost:8083
          predicates:
            - Path=/feeds/**,
        - id: bambam-front
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - '*'
            allowedMethods:
              - '*'
            allowedHeaders:
              - '*'
            allowCredentials: true
---
spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/**,
        # - id: delivery
        #   uri: http://delivery:8080
        #   predicates:
        #     - Path=/deliveries/**,
        # - id: product
        #   uri: http://product:8080
        #   predicates:
        #     - Path=/inventories/**,
        - id: pet
          uri: http://pet:8080
          predicates:
            - Path=/pets/**,
        - id: feed
          uri: http://feed:8080
          predicates:
            - Path=/feeds/**,
        - id: bambam-front
          uri: http://bambam-front:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - '*'
            allowedMethods:
              - '*'
            allowedHeaders:
              - '*'
            allowCredentials: true

server:
  port: 8080
